package com.tecoloteinc.bosses.Sprites.Characters;

import com.badlogic.gdx.math.MathUtils;
import com.tecoloteinc.bosses.GameEngine;
import com.tecoloteinc.bosses.utils.AnimationsFolder.GameAnimations;
import com.tecoloteinc.bosses.utils.AnimationsFolder.AnimationsEngine;
import com.tecoloteinc.bosses.Sprites.SpriteObject;

import static com.tecoloteinc.bosses.utils.Others.GameConstants.*;

/**
 * Class Character used to generate any character in the game
 * This class must be inherited by other NPC, GamePlayer or enemy types.
 */
public abstract class Character extends SpriteObject {

    /*********************************************
     * Properties of any Character
     ********************************************/
    /**
     * Signals from Any Sprite.
     */
    public enum GameSignals {
        /**
         * Generated when the Sprite arrives a the pending coordinates.
         */
        SIGNAL_REACHED_DESTINATION,
        /**
         * Generated when the game request a Stop() call resetting coordinates
         */
        SIGNAL_STOP_DESTINATION,
        /**
         * Generated when the Sprite collides with a Block Type, before arriving
         * to the pending coordinates
         */
        SIGNAL_BLOCKED_DESTINATION,

        SIGNAL_ELAPSED_TIME,
        /**
         * SIGNALS HERE
         */
        SIGNAL_OTHER_SIGNAL
    }

    /**
     * Static variables used to control the
     * side of the Sprite Object
     */
    public final static int RIGHT = 0;
    public final static int LEFT = 1;
    public final static int UP = 2;
    public final static int DOWN = 3;
    public final static int EXPLODING = 4;

    /**
     * Controls the speed of the character
     */
    protected float speed;
    /**
     * Controls if the Character could be shown
     */
    protected boolean visible;
    /**
     * Is the Sprite Block (unable to be moved by controls)
     */
    protected boolean isBlocked = false;

    /**
     * Used to enable the signal ReachedXY
     */
    private boolean activeSignalReach = false;
    /**
     * Used to let the character walk to the
     * pending_x/y_coordinates.
     */
    private boolean enabledWalking = false;

    /**
     * Position required for the Character X
     */
    protected float m_pending_x_coord;
    /**
     * Position required for the Character Y
     */
    protected float m_pending_y_coord;

    /**
     * Monitors the time to execute the animations based
     * in the configurations specified in the constructor.
     */
    private float animationTimer;
    /**
     * Variable to control the signals generated by a timer
     */
    private float signalTimer;
    /**
     * This time is set by the user, to trigger the
     * timer signal.
     */
    private float userDefinedTime;
    /**
     * Timer is measured when this variable is true.
     */
    private boolean activeSignalTimer = false;
    /**
     * Timer used to execute the SignalHandler function
     * cycled.
     */
    private float signalHandlerTimer;
    /**
     * Controls the duration of each animation frame
     */
    protected float animationDuration;

    /**
     * @TODO Oscar's change.
     */
    protected com.tecoloteinc.bosses.utils.Others.MotionModel motion;

    /**
     * Controls the type of animation.
     * These animations should be mid-high level
     * animations. AnimationsEngine common for all Characters.
     */
    private enum AnimationTypes {
        ANIMATION_IDLE,
        ANIMATION_WALKING,
        ANIMATION_ATTACKING,
        ANIMATION_ATTACKED,
        ANIMATION_DYING
    }

    private boolean enabledAttacking = false;

    public AnimationsEngine animationsEngineHandler = new AnimationsEngine();
    AnimationTypes m_currentAnimation = AnimationTypes.ANIMATION_IDLE;

    /**
     * This Constructor creates the Character sprite with no default
     * all characteristics are to be defined.
     *
     * @param Speed              Sets the speed of the Character.
     * @param Visible            Sets the visibility of the object.
     * @param TexturePath        Path of the texture.
     * @param h_frames           Number of horizontal frames of the Animation.
     * @param v_frames           Number of vertical frames.
     * @param animation_duration Animation time of each frame.
     */
    public Character(GameEngine game_ref, float Speed, boolean Visible,
                     String TexturePath, int h_frames, int v_frames, float animation_duration) {
        super(game_ref);
        speed = Speed;
        visible = Visible;
        animationDuration = animation_duration;
        /**
         *  Set the region and the Size of the frame.
         *  and establishes the first frame as the
         *  current texture.  */
        loadTexture(TexturePath, h_frames, v_frames);
        //motion = new SimpleMotionModel(speed);
        // Position this Sprite in the center, this is to make more compatibility with the TiledMap
        setPosition(50, 50);
    }

    /**
     * Get the state of the isBlocked property.
     *
     * @return true if the Character can be moved.
     */
    public boolean getIsBlocked() {
        return isBlocked;
    }

    /**
     * set the state of the isBlocked property.
     *
     * @return true if the Character can be moved.
     */
    public void setIsBlocked(boolean state) {
        isBlocked = state;
    }

    /**
     * @param model
     * @TODO: 7/6/16 Add header.
     */
    public void setMotion(com.tecoloteinc.bosses.utils.Others.MotionModel model) {
        motion = model;
    }

    /**
     * This method activates the animated movement of the Character. Will start moving the
     * Character to the _x, _y position during the execution of the Game until the
     * Character reaches the desired position.
     *
     * @param _x Desired x cord.
     * @param _y Desired y cord.
     */
    public void gotoXY(float _x, float _y) {
        if (AnimationTypes.ANIMATION_IDLE == m_currentAnimation ||
                AnimationTypes.ANIMATION_WALKING == m_currentAnimation) {
            /** @TODO Oscar's Change has issue.*/
            //motion.setTargetPosition((float) _x, (float) _y);
            m_pending_x_coord = _x;
            m_pending_y_coord = _y;
            m_currentAnimation = AnimationTypes.ANIMATION_WALKING;
            enabledWalking = true;
            /** Enable Signaling handler. */
            activeSignalReach = true;
        }
    }

    public void attack() {
        //stop();
        //m_currentAnimation = AnimationTypes.ANIMATION_ATTACKING;
        //enabledAttacking = true;
        setIsBlocked(true);
        stop();
        animationsEngineHandler.setNewAnimation(GameAnimations.attack(), 1, true, getCurrentVerticalAnimation(), getCurrentVerticalAnimation()+4, false);
        //animationsEngineHandler.setNewAnimation
    }

    public void die() {
        //stop();
        //m_currentAnimation = AnimationTypes.ANIMATION_ATTACKING;
        //enabledAttacking = true;
        animationsEngineHandler.setNewAnimation(GameAnimations.die(), 1, true, 8, false);

        isBlocked=true;
    }

    /**
     * Stop the walk of the character.
     * This function reset the pending coordinates xy, and
     * raises the SIGNAL_STOP_DESTINATION signal.
     */
    public void stop() {
        if (m_currentAnimation == AnimationTypes.ANIMATION_WALKING) {
            enabledWalking = false;
            // Reach the desired position intentionally.
            m_pending_x_coord = getX();
            m_pending_y_coord = getY();
            m_currentAnimation = AnimationTypes.ANIMATION_IDLE;
            /** @TODO Oscar's change has an issue.
            motion.setTargetPosition(getX(), getY());*/
            receivedSignal(GameSignals.SIGNAL_STOP_DESTINATION);
        }
    }

    /**
     * Activate the monitor for the Timer Signal. Once this method
     * is called, the timer start running and raises the
     * SIGNAL_ELAPSED_TIME signal.
     *
     * @param time_in_seconds time to rise the signal.
     */
    public void waitTime(float time_in_seconds) {
        signalTimer = 0;
        userDefinedTime = time_in_seconds;
        // Reset the frame.
        updateAnimation(getCurrentHorizontalAnimation(), getCurrentVerticalAnimation());
        // Enable the signal for timers.
        activeSignalTimer = true;
    }

    /**
     * This function is executed all the time
     * and is used to perform the animation independently
     * of what animation. The type of animation is set
     * with another method
     * Put here only High End AnimationsEngine, basic ones should be in SpriteObject.
     */
    public void animating() {
        switch (m_currentAnimation) {
            case ANIMATION_IDLE: {
                    updateAnimation(current_h_frame, getCurrentVerticalAnimation());
                break;
            }
            case ANIMATION_WALKING: {
                if ((0 == current_h_frame) || (current_h_frame >= m_HFrames)) {
                    current_h_frame = 1;
                    //playSound(SFX_WALKING);
                }
                if (enabledWalking) {
                    /** @TODO Oscar's Change.
                    Point2f delta = Point2f.diff(motion.getTargetPosition(), motion.getCurrPosition());
                    delta_x = delta.pX;
                    delta_y = delta.pY;*/
                    getLookingSide();
                    updateAnimation(current_h_frame, getCurrentVerticalAnimation());
                    current_h_frame++;
                }
                break;
            }
            /**
             *
             *  @TODO ANIMATION_DYING
             *  @TODO ANIMATION_SOMETHING...
             */
        }
    }

    /**
     * This method get the correct position of the Sprite
     * this mean the correct Texture region.
     */
    protected void getLookingSide() {
        float delta_x = m_pending_x_coord - getX();
        float delta_y = m_pending_y_coord - getY();

        /** Sprite needs to see to Right or Up? */
        if ((delta_x >= 0) && (delta_y >= 0)) {
            if (Math.abs(delta_x) > Math.abs(delta_y)) {
                setCurrentAnimation(RIGHT);
            } else {
                setCurrentAnimation(UP);
            }
        }
        /** Hero needs to see to Left or Up? */
        if ((delta_x <= 0) && (delta_y >= 0)) {
            if (Math.abs(delta_x) > Math.abs(delta_y)) {
                setCurrentAnimation(LEFT);
            } else {
                setCurrentAnimation(UP);
            }
        }
        /** Sprite needs to see to Right or Down? */
        if ((delta_x >= 0) && (delta_y <= 0)) {
            if (Math.abs(delta_x) > Math.abs(delta_y)) {
                setCurrentAnimation(RIGHT);
            } else {
                setCurrentAnimation(DOWN);
            }
        }
        /** Sprite needs to see to Left or Down? */
        if ((delta_x <= 0) && (delta_y <= 0)) {
            if (Math.abs(delta_x) > Math.abs(delta_y)) {
                setCurrentAnimation(LEFT);
            } else {
                setCurrentAnimation(DOWN);
            }
        }
    }

    /**
     * This function is used to process the signals to be sent to
     * the character. Trigger here any signal needed in the final character class.
     *
     * @param delta Time in seconds since last call to this function.
     */
    private void CharSignalHandler(float delta) {
        if (activeSignalTimer) {
            signalTimer += delta;
        }

        /**************************************************************
         *  Signal raised when Character reaches pending_coordinates  *
         *  SIGNAL_REACHED_DESTINATION
         **************************************************************/
        if ((activeSignalReach)
                && (getX() > (m_pending_x_coord - (speed * delta * 60)) && (getX() < (m_pending_x_coord + (speed * delta * 60))))
                && (getY() > (m_pending_y_coord - (speed * delta * 60)) && (getY() < (m_pending_y_coord + (speed * delta * 60))))) {
            receivedSignal(GameSignals.SIGNAL_REACHED_DESTINATION);

            // Set to false, to avoid multiple signals.
            activeSignalReach = false;
        }

        if (wasPreviouslyBlocked()) {
            //activeSignalReach = false;
            receivedSignal(GameSignals.SIGNAL_BLOCKED_DESTINATION);

        }
        /** @TODO Oscar's Change, has an issue.
        if ((activeSignalReach) && motion.reachedTarget()) {
        receivedSignal(GameSignals.SIGNAL_REACHED_DESTINATION);
        // Set to false, to avoid multiple signals.
        activeSignalReach = false;
        }*/
        /**************************************************************
         * Check if the time set by waitForTime has been elapsed      *
         * to trigger a signal. Only works when the activeSignalTimer *
         * is true.    SIGNAL_ELAPSED_TIME                            *
         *************************************************************/

        if ((signalTimer >= userDefinedTime) && (activeSignalTimer)) {
            activeSignalTimer = false;
            userDefinedTime = 0;
            signalTimer = 0;
            receivedSignal(GameSignals.SIGNAL_ELAPSED_TIME);
        }

        /**
         * @TODO SIGNAL_GETHIT
         */
    }

    /**
     * This is the function that is going to be executed in the
     * Character class. @TODO set abstract.
     *
     * @param signal Signal to be sent to the Character class.
     */
    public void receivedSignal(GameSignals signal) {
    }

    /**
     * loop function to called animating and execute the next layer
     * implementation.
     */
    public void executive(float delta) {
        AnimationsEngine.AnimationSequenceType frames;
        animationTimer += delta;
        signalHandlerTimer += delta;


        if ((null != animationsEngineHandler) && (animationsEngineHandler.isAnimationValid())) {
            frames = animationsEngineHandler.getFrame(delta);
            setFrame(frames.horizontal_frame, frames.vertical_frame);
            updateAnimation(frames.horizontal_frame, frames.vertical_frame );
            /** If @code{isAnimationValid()} is true, it means that the invalidation occurred while
             * grabbing the frame but it was not valid anymore, is time to process the ending of
             * the animations*/
            if (!animationsEngineHandler.isAnimationValid()) {
                setIsBlocked(false);
            }
        } else {
            // Timer for AnimationsEngine
            if (animationTimer > animationDuration) {
                animating();
                animationTimer = 0;
            }
        }
        /** @TODO Check the better timer for the Magic Number. */
        // Timer for Processing Signals.
        if (signalHandlerTimer > SPT) {
            CharSignalHandler(delta);
        }
        /** when the Character needs to walk to some point */
        Walking(delta);
        // Execute next layer loop.
        loop();
    }

    /**
     * Abstract function executed by the last implementation of the this
     * class, used to do what ever your Character want to do.
     */
    public abstract void loop();

    /**
     * Abstract function to execute the sound in the final child class
     * each enemy has to define their own list of sounds effects,
     * this class will call each one according to the list.
     */
    public void playSound(int soundFx) {
        /** @TODO add code here for sounds */
    }

    /**
     * Abstract function to make the Character to walk.
     * This function is executed every cycle if not overridden.
     * This default function puts the Character to pursuit the
     * pending coordinates only when enabledWalking is true.
     */
    public void Walking(float delta) {
        if ((0 != current_h_frame) && (enabledWalking)) {
            float angle = MathUtils.atan2(m_pending_y_coord - getY(), m_pending_x_coord - getX());
            // Multiply by delta * 60 to normalize movement based on 60 FPS reference.
            move_x(speed * MathUtils.cos(angle) * delta * 60);
            move_y(speed * MathUtils.sin(angle) * delta * 60);

            /** Oscar's Change, has an issue.
             motion.updateModel(delta);
             Point2f step = motion.getStep();
             move_x(step.pX);
             move_y(step.pY);*/

        }
    }

    /*********************************************
     * Getters of any Character
     ********************************************/

    /**
     * Getter for the speed property.
     *
     * @return speed property.
     */
    public float getSpeed() {
        return speed;
    }


}



